import { GoogleGenerativeAI } from '@google/generative-ai';
import fetch from 'node-fetch'
import config from '../config.js';
import axios from 'axios';
import FormData from 'form-data';
import mime from 'mime-types';
import { join } from 'path';
import { readFileSync, unlinkSync } from 'fs';
import gtts from 'gtts'; 
import { v4 as uuidv4 } from 'uuid';

const createSuccessResponse = (data, modelUsed, logicUsed) => ({
  success: true,
  creator: "Parhan cina",
  data,
  metadata: {
    modelUsed,
    logicUsed: logicUsed || config.defaultLogic,
    length: data.length,
  },
});

// BLACKBOX
async function blackbox(text, logic, model) {
  try {
    const prompt = `${logic ? `${logic}\n` : ''}${text}`;
    const url = 'https://api.blackbox.ai/api/chat';
    const data = {
      "messages": [{ "role": "user", "content": prompt, "id": "QgaYVnl" }],
      "id": "ugrC6k4",
      "previewToken": null,
      "userId": null,
      "codeModelMode": true,
      "agentMode": {},
      "trendingAgentMode": {},
      "isMicMode": false,
      "userSystemPrompt": null,
      "maxTokens": 1024,
      "playgroundTopP": 0.9,
      "playgroundTemperature": 0.5,
      "isChromeExt": false,
      "githubToken": "",
      "clickedAnswer2": false,
      "clickedAnswer3": false,
      "clickedForceWebSearch": false,
      "visitFromDelta": false,
      "mobileClient": false,
      "userSelectedModel": null,
      "validated": "00f37b34-a166-4efb-bce5-1312d87f2f94"
    };
    const headers = { 'Content-Type': 'application/json' };
    const result = await callAPI(url, 'POST', data, headers);
    const cleanedResult = result.replace("Generated by BLACKBOX.AI, try unlimited chat https://www.blackbox.ai", "").trim();
    return createSuccessResponse(cleanedResult, model || "Blackbox", logic); 
  } catch (error) {
    console.error('Error processing with Blackbox:', error);
    throw new Error(`Blackbox Error: ${error.message}`);
  }
}

// GEMINI
async function gemini(text, logic, model) {
  try {
    const usedApiKey = process.env.GOOGLE_API_KEY;
    const genAI = new GoogleGenerativeAI(usedApiKey);
    const systemLogic = logic || config.defaultLogic;
    const modell = genAI.getGenerativeModel({
      model: model || config.defaultModel,
      systemInstruction: systemLogic,
    });
    const resultp = await modell.generateContent(text);
    if (!resultp.response || !resultp.response.candidates || resultp.response.candidates.length === 0) {
      throw new Error("Respons dari layanan AI tidak valid. Mungkin API Gemini sedang down");
    }
    const responseText = resultp.response.candidates[0]?.content?.parts?.[0]?.text?.trimEnd() || "";
    return createSuccessResponse(responseText, model || config.defaultModel, logic);
  } catch (err) {
    console.error('Error processing with Gemini:', err);
    throw new Error(`Gemini Error: ${err.message}`);
  }
}

// REMOVE BG
async function removebg(imageURL) {
  try {
    const imageResponse = await axios.get(imageURL, { responseType: 'arraybuffer' });
    const mimeType = mime.lookup(imageURL) || 'image/jpeg';
    const imageBuffer = Buffer.from(imageResponse.data);

    const formData = new FormData();
    formData.append('size', 'auto');
    formData.append('image_file', imageBuffer, {
      filename: 'upload.jpg',
      contentType: mimeType
    });

    const response = await fetch("https://api.remove.bg/v1.0/removebg", {
        method: "POST",
        headers: { "X-Api-Key": "SgEo63fvZ7XaBWbbc3J925Hd" },
        body: formData,
    });
    if (response.status === 200) { 
      let hasil = await response.buffer();
      return hasil;
    } else {
      const errorDetails = await response.data;
      throw new Error(`Remove.bg API Error: ${response.status} - ${errorDetails}`);
    }
  } catch (error) {
    console.error('Error in removebg:', error);
    throw new Error(`Remove BG Error: ${error.message}`);
  }
}

// GOOGLE TTS
async function generateTTS(text, lang = 'id') {
  console.log(lang, text);
  return new Promise((resolve, reject) => {
    try {
      const tts = new gtts(text, lang);
      const filePath = join(global.__dirname(import.meta.url), '../tmp', uuidv4() + '.wav'); 

      tts.save(filePath, (err, result) => {
        if (err) {
          reject(err); 
        } else {
          resolve(readFileSync(filePath));
          unlinkSync(filePath); 
        }
      });
    } catch (e) { 
      reject(e); 
    }
  });
}
async function googletts(text, lang = 'id') { 
  try {
    const audioBuffer = await generateTTS(text, lang);
    return audioBuffer;
  } catch (error) {
    console.error('Error in googletts:', error); 
    throw new Error(`Google TTS Error: ${error.message}`);
  }
}

export {
  blackbox,
  gemini,
  removebg,
  googletts,
};
